### ISSUE TITLE
HTTP 400 from Google (googleapiclient.errors.HttpError:)

### ISSUE THREAD

**Issue by oriongplays** [ThioJoe/Auto-Synced-Translated-Dubs#48]
Hello!

I've tried using, but I'm getting error 400 from Google.

![errror400](https://user-images.githubusercontent.com/67943379/214115564-7f8ca4e0-7075-425f-a3f0-b89a4c5ce8ba.png)

Any ideias? I've tried reseting my client secret but that didn't worked

Also here is the SRT file: 
[subtitles.zip](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/files/10482489/subtitles.zip)

 ```----- Beginning Processing of Language: es-MX -----
Translating text using Google...
Traceback (most recent call last):
  File "D:\auto-dub\main.py", line 262, in <module>
    process_language(langData)
  File "D:\auto-dub\main.py", line 240, in process_language
    individualLanguageSubsDict = translate.translate_dictionary(individualLanguageSubsDict, langDict, skipTranslation=skipTranslation)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\auto-dub\translate.py", line 169, in translate_dictionary
    ).execute()
      ^^^^^^^^^
  File "C:\Users\pdv\AppData\Local\Programs\Python\Python311\Lib\site-packages\googleapiclient\_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pdv\AppData\Local\Programs\Python\Python311\Lib\site-packages\googleapiclient\http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 400 when requesting https://translation.googleapis.com/v3beta1/projects/your-project-name:translateText?alt=json returned "Invalid 'parent'.; Invalid resource name. Missing locations/ part.;  Resource type: location". Details: "Invalid 'parent'.; Invalid resource name. Missing locations/ part.;  Resource type: location"> ```

**Comment by ThioJoe** [comment]
This is because you haven't set the `google_project_id` in the `cloud_service_settings.ini` file.
