### ISSUE TITLE
Missing modules in requirements.txt

### ISSUE THREAD

**Issue by VikingKing** [ThioJoe/Auto-Synced-Translated-Dubs#5]
import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by ThioJoe** [comment]
Ah that's not actually necessary, just fixed it

**Comment by SweetSofiMC** [comment]
I think numpy is actually needed, not by the code itself, but for pyrubberband to work.

In a fresh install with a virtual environment, I got this error after running python main.py:

```
Traceback (most recent call last):
  File "Auto-Synced-Translated-Dubs\main.py", line 11, in <module>
    import audio_builder
  File "Auto-Synced-Translated-Dubs\audio_builder.py", line 3, in <module>
    import pyrubberband
  File "Auto-Synced-Translated-Dubs\venv\lib\site-packages\pyrubberband\__init__.py", line 6, in <module>
    from .pyrb import *
  File "Auto-Synced-Translated-Dubs\venv\lib\site-packages\pyrubberband\pyrb.py", line 18, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

This was fixed by doing `pip install numpy`, so adding numpy to the `requirements.txt` file should also fix it for everyone.
