### ISSUE TITLE
Error after setting batch_tts_synthesize = True

### ISSUE THREAD

**Issue by yhmickey** [ThioJoe/Auto-Synced-Translated-Dubs#56]
Failed to submit batch synthesis job: {
  "code": "Forbidden",
  "message": "Only \"Standard\" subscriptions for the region of the called service are valid."
}
Traceback (most recent call last):
  File "E:\01project\12youtube\02program\Auto-Synced-Translated-Dubs\main.py", line 262, in <module>
    process_language(langData)
  File "E:\01project\12youtube\02program\Auto-Synced-Translated-Dubs\main.py", line 253, in process_language
    individualLanguageSubsDict = audio_builder.build_audio(individualLanguageSubsDict, langDict, totalAudioLength, twoPassVoiceSynth)
  File "E:\01project\12youtube\02program\Auto-Synced-Translated-Dubs\audio_builder.py", line 100, in build_audio
    rawClip = AudioSegment.from_file(value['TTS_FilePath'], format="mp3", frame_rate=nativeSampleRate)
KeyError: 'TTS_FilePath'

I use the latest code.  The project can work well  when batch_tts_synthesize  is set False.
Please check it. 
Thank you.

**Comment by ThioJoe** [comment]
The message describes the problem: `Only "Standard" subscriptions for the region of the called service are valid.`

Azure doesn't allow batch processing for free accounts. Just disable batch processing in the config.
