### ISSUE TITLE
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

### ISSUE THREAD

**Issue by lvance18** [ThioJoe/Auto-Synced-Translated-Dubs#65]
I am having lots of different issues. Here is the latest:

------- 'Auto Synced Translated Dubs' script by ThioJoe - Release version 0.14.1 -------

----- Beginning Processing of Languages -----

----- Beginning Processing of Language (1/1): en-US -----
Original language is the same as the target language. Skipping translation.

Traceback (most recent call last):
  File "c:\Laurence\main.py", line 282, in <module>
    process_language(langData, processedCount, totalLanguages)
  File "c:\Laurence\main.py", line 268, in process_language
    individualLanguageSubsDict = audio_builder.build_audio(individualLanguageSubsDict, langDict, totalAudioLength, config['two_pass_voice_synth'])
  File "c:\Laurence\Scripts\audio_builder.py", line 76, in build_audio
    rawClip = AudioSegment.from_file(value['TTS_FilePath'], format="mp3", frame_rate=int(config['synth_sample_rate']))
  File "C:\Users\linds\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\pydub\audio_segment.py", line 773, in from_file
    raise CouldntDecodeError(
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version N-110402-ge3143703e9-20230427 Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.152_89671bf)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20230427
  libavutil      58.  6.100 / 58.  6.100
  libavcodec     60. 10.100 / 60. 10.100
  libavformat    60.  5.100 / 60.  5.100
  libavdevice    60.  2.100 / 60.  2.100
  libavfilter     9.  5.100 /  9.  5.100
  libswscale      7.  2.100 /  7.  2.100
  libswresample   4. 11.100 /  4. 11.100
  libpostproc    57.  2.100 / 57.  2.100
[mp3 @ 000002572bd69500] Failed to read frame size: Could not seek to 1026.
workingFolder\1.mp3: Invalid argument

**Comment by AdnielSsj** [comment]
Good morning, I'll assume that you're trying to use Azure. If you want to do a batch job in Azure, you need a standard subscription and not a free one. Also, make sure that the "azure_speech_key" and "azure_speech_region" are correct for your Azure project.

![image](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/assets/121997647/6a5dd402-ffd8-46d6-ae27-fa08ce0d57ed)

![image](https://github.com/ThioJoe/Auto-Synced-Translated-Dubs/assets/121997647/87eaddab-10a5-4b99-9b64-8aad9630d12a)
