### ISSUE TITLE
Please login using the browser window that opened just now.  Error: Client secrets must be for a web or installed app.

### ISSUE THREAD

**Issue by zhibinlin1** [ThioJoe/Auto-Synced-Translated-Dubs#68]
Please login using the browser window that opened just now.

Traceback (most recent call last):
  File "C:\Users\lzb\Auto-Synced-Translated-Dubs-0.14.1\Scripts\auth.py", line 147, in first_authentication
    GOOGLE_TTS_API, GOOGLE_TRANSLATE_API = get_authenticated_service() # Create authentication object
  File "C:\Users\lzb\Auto-Synced-Translated-Dubs-0.14.1\Scripts\auth.py", line 105, in get_authenticated_service
    flow = InstalledAppFlow.from_client_secrets_file(secrets_file, scopes=API_SCOPES)
  File "C:\Users\lzb\AppData\Local\Programs\Python\Python39\lib\site-packages\google_auth_oauthlib\flow.py", line 201, in from_client_secrets_file
    return cls.from_client_config(client_config, scopes=scopes, **kwargs)
  File "C:\Users\lzb\AppData\Local\Programs\Python\Python39\lib\site-packages\google_auth_oauthlib\flow.py", line 159, in from_client_config
    raise ValueError("Client secrets must be for a web or installed app.")
ValueError: Client secrets must be for a web or installed app.
----------------
[!!!] Error: Client secrets must be for a web or installed app.

Error: Something went wrong during authentication. Try deleting the token.pickle file.
Press Enter to Exit...

**Comment by AdnielSsj** [comment]
Good morning, you need to accept the use of the Google account that you have configured for Google APIs. That being said, you also have to select the same account with which you created the translation and TTS APIs.
